GET http://localhost:8000/api/get_exam_question_list/

###

POST http://localhost:8000/api/post_exam_result/
Content-Type: application/json

[
  {
    "questionId": "1",
    "answer": true
  },
  {
    "questionId": "1",
    "answer": false
  }
]

###
GET http://localhost:8000/api/get_salary_list/

###
POST http://localhost:8000/api/get_user_interview_list/
Content-Type: application/json

{
    "userId": "3212901134"
}
