# Generated by Django 5.1.3 on 2025-03-07 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20241116_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCurriculumVitae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=20)),
                ('answer', models.BooleanField()),
                ('file', models.FileField(upload_to='test_curriculum_vitae_file')),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluationuser',
            name='isTeacher',
        ),
        migrations.RemoveField(
            model_name='evaluationuser',
            name='score_test1',
        ),
        migrations.RemoveField(
            model_name='evaluationuser',
            name='stage',
        ),
        migrations.AddField(
            model_name='evaluationuser',
            name='account',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='evaluationuser',
            name='accountHolderName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='evaluationuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationuser',
            name='bank',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='evaluationuser',
            name='bankCard',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='evaluationuser',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evaluationuser',
            name='idCard',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('post', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='curriculum_vitae_file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CurriculumVitaeUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewId', models.CharField(max_length=20, unique=True)),
                ('interviewTime', models.DateTimeField()),
                ('post', models.CharField(max_length=20)),
                ('isAgreed', models.BooleanField(default=False)),
                ('isArrived', models.BooleanField(default=False)),
                ('commuteTime', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('curriculumVitae', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CurriculumVitae', to='server.curriculumvitae')),
            ],
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CurriculumVitaeInterview', to='server.interview'),
        ),
    ]
