# Generated by Django 5.1.3 on 2025-03-07 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_testcurriculumvitae_remove_evaluationuser_isteacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='user',
        ),
        migrations.AddField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CurriculumVitaeUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
