# Generated by Django 5.1.3 on 2025-03-07 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_curriculumvitae_user_interview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='student',
        ),
        migrations.AddField(
            model_name='activity',
            name='hr',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HR', to=settings.AUTH_USER_MODEL),
        ),
    ]
