# Generated by Django 5.1.3 on 2025-03-10 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_activity_hr_activity_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcurriculumvitae',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcurriculumvitae',
            name='numTest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcurriculumvitae',
            name='passTime',
            field=models.IntegerField(default=0),
        ),
    ]
