# Generated by Django 5.1.3 on 2025-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_testcurriculumvitae_createtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interviewId',
            field=models.CharField(auto_created=True, max_length=20, unique=True),
        ),
    ]
