# Generated by Django 5.1.3 on 2025-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_interview_interviewid'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewee',
            field=models.CharField(default='', max_length=20),
        ),
    ]
