# Generated by Django 5.1.3 on 2025-03-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_interview_interviewee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='curriculumVitae',
        ),
    ]
