# Generated by Django 5.1.3 on 2025-03-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_remove_interview_curriculumvitae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interviewId',
        ),
    ]
