# Generated by Django 5.1.3 on 2025-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_remove_interview_interviewid'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='settlement',
            field=models.BooleanField(default=False),
        ),
    ]
