# Generated by Django 5.1.3 on 2025-03-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_delete_testcurriculumvitae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='interview',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CurriculumVitaeInterview', to='server.interview'),
        ),
    ]
