# Generated by Django 5.1.3 on 2025-03-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_alter_curriculumvitae_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationuser',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
    ]
