# Generated by Django 5.1.3 on 2025-03-12 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_evaluationuser_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlementTime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('bankCard', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=30)),
                ('accountHolderName', models.CharField(max_length=30)),
                ('idCard', models.CharField(max_length=30)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='SettlementUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
