# Generated by Django 5.1.3 on 2025-03-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationuser',
            name='payDay',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
